spring:
  profiles:
    active: dev
  application:
    name: msb-arica
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/public/,file:d:/dev/upload/
# 对应的sql映射
mybatis:
 mapper-locations: classpath:mapper/*.xml
