#指定启动环境 ， 可以改为入参的方式
spring:
  profiles:
    active: dev
  application:
    name: msb-test
#配置坦克数量
tanksCount: 8
goodsFS: com.cn.tank.FourFireStrategy
badFS: DefaltFireStrategy
colliderList: com.cn.cor.BulletTankCollider,com.cn.cor.TankTankCollider